trigger:
  - master

pool:
  vmImage: 'Ubuntu 18.04'

variables:
  azureSubscriptionEndpoint: malliina
  DockerNamespace: malliinacr.azurecr.io
  DockerRepository: mavenapi
  WebAppName: malliinamavenapi
  SbtVersion: 1.4.4

steps:

  - script: wget https://dl.bintray.com/sbt/debian/sbt-$(sbtVersion).deb
    displayName: 'Download sbt'

  - script: sudo dpkg -i sbt-$(sbtVersion).deb
    displayName: 'Install sbt'

  - script: sbt test
    displayName: 'Compile'

  - task: Docker@2
    displayName: Login to ACR
    inputs:
      command: login
      containerRegistry: malliinaregistry

  - script: sbt docker:publish
    displayName: 'Push to ACR'

  - task: AzureRMWebAppDeployment@4
    displayName: Azure App Service Deploy
    inputs:
      appType: webAppContainer
      ConnectedServiceName: $(azureSubscriptionEndpoint)
      WebAppName: $(WebAppName)
      DockerNamespace: $(DockerNamespace)
      DockerRepository: $(DockerRepository)
      DockerImageTag: $(Build.SourceVersion)
      DeployToSlotFlag: true
      SlotName: true

  - task: Docker@2
    displayName: Logout of ACR
    inputs:
      command: logout
      containerRegistry: malliinaregistry
