name: Test

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04

    services:
      mysql:
        image: mariadb:10.11.6
        env:
          MYSQL_DATABASE: testapi
          MYSQL_USER: testapi
          MYSQL_PASSWORD: testdb123
          MYSQL_ROOT_PASSWORD: testdb123
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Run tests
        env:
          DB_PASS: testdb123
        run: sbt test
