name: Deploy

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@master

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"

      - uses: azure/docker-login@v1
        with:
          login-server: malliinacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          sbt docker:publish

      - name: 'Deploy to Azure'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'malliinamavenapi'
          images: 'malliinacr.azurecr.io/mavenapi:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
