name: Build

on:
  push:
    branches:
      - master

env:
  A: b

jobs:
  deploy:
    name: Build deb
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install lintian
        run: |
          sudo apt-get update
          sudo apt-get install -y lintian
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          cache: sbt
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ga.key
          chmod 600 ~/.ssh/ga.key
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ga.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
      - name: Build with sbt
        run: |
          sbt "mode prod" compile
          sbt "mode prod" Deb/packageBin
      - name: Deploy
        run: |
          scp backend/target/api.deb server:/home/mle/api.deb
          ssh server 'sudo dpkg --force-confold -i /home/mle/api.deb'
